(ns muse.page.about
  (:require [compojure.core :refer :all]
            [hiccup.core :refer :all]
            [hiccup.page :refer :all]
            [muse.page.page :as pg]
            [muse.page.head :as mhd]))

(defn about []
   
   [:head 
    [:title "Butter Notes | About"]
    [:meta {:description "Information About Butter Notes"}]
    (for [x (mhd/headers {:head-type "global"})]
      x)]
   
   [:div.row
    [:h1 {:style "font-size:2em;"} "About Butter Notes"]

    [:h2 {:style "font-size:1.5em;"} "Me"]
    [:p "My Name is David. If you have any feedback, ideas, or found any mistakes, please contact me at "
     [:a {:href "mailto:david.t@butternotes.com?subject=Feedback for butternotes.com"} "david.t@butternotes.com"] ". I'm aware of the 404 pages."]

    [:p "I don't work with any particular company, as I'm stictly an inpendent programmer and contractor. If you would like to hire me to help
with your project, feel free to contact me at " [:a {:href "mailto:david.t@butternotes.com?subject=Feedback for butternotes.com"} "david.t@butternotes.com"] "."]
    
    [:p [:b "Twitter"] ": " [:a {:href "https://twitter.com/ButternotesWeb"}
                             "@ButternotesWeb"]]
    [:p [:b "Facebook"] ": " [:a {:href "https://www.facebook.com/butternotescom-1735463286766016/"}
                              "butternotes"]]

    [:h2 {:style "font-size:1.5em;"} "Tech and Approach"]
    [:p "Butter Notes is written in "
     [:a {:href "https://clojure.org/"} "Clojure"] ". The scales are generated on the fly. The system generates "
     [:a {:href "https://www.musicxml.com/"} "MusicXML"] " and feeds it into "
     [:a {:href "http://wim.vree.org/js/"} "abcweb"] ", which renders SVG music sheet. The sound is generated by "
     [:a {:href "https://github.com/rserota/wad"} "Wad"] "."]
    [:p "The sheet music code generation is based off the concepts I've written about in "
     [:a {:href "https://www.coderedux.com/"} "{:Code Redux}"] "."]

    [:h2 {:style "font-size:1.5em;"} "Short FAQ"]
    [:p [:b "I want to submit myself for your review pages!"]]
    [:p "You are more than welcome to do so, but...."]
    [:p "The point of that section is to only do positive reviews, meaning I will
only talk about music I enjoy, so it's not personal if I never do review your work. I'll write
back letting you know I have the submission; please don't do follow-up emails."]
    
    [:p [:b "Are you going to do tabs?"]]
    [:p "No. You can read the article on why " [:a {:href "/blog/why-no-tabs"} "Here"] "."]

    [:p [:b "What is the point?"]]
    [:p ":("]
    [:p "The ultimate goal is to do sheet music generation. ie: You can play your instrument into the system and it will generate sheet music.
I'm not sure how possible it will be, but hey, it's a goal."]

    [:p [:b "The site looks terrible. My professional design company..."]]
    [:p "Sorry, the budget for this project is currently my time and hosting fees."]
    [:p "If you are someone looking for something to build up his or her portfolio, then by all means, contact me if you want to do
pro bono or deferred payment. When I do have the budget for a designer, I'll post about here. I'd rather pay someone who is starting out than a 
company, not because I'm cheap, but altruistic."]])
